
project_id = "iasrhvglfayqogxkfaiw"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovableproject.com"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = true

[functions.instagram-starapi]
verify_jwt = true

[functions.instagram-data-sync]
verify_jwt = false

[functions.instagram-csv-export]
verify_jwt = true

[functions.instagram-cron-sync]
verify_jwt = false

[functions.generate-brandbook]
verify_jwt = true

[functions.generate-image]
verify_jwt = true
