// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iasrhvglfayqogxkfaiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlhc3JodmdsZmF5cW9neGtmYWl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3Mjk4NTksImV4cCI6MjA2NzMwNTg1OX0.-NUi-4OhvdI-3PoEETEC5TmxE0EanWQcsRUbg13mXGc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});